### ISSUE TITLE
extension kullanımı ve assetler

### ISSUE THREAD

**Issue by akaanuzman** [umutsa177/travel_App#3]
https://github.com/umutsa177/travel_App/blob/57e524eb3f1b2ee81a4e409fc37e02db990d21d1/lib/models/natural_destination_model.dart#L11

böyle kullanımı bi kaç yerde daha gördüm string'e bir extension yazıp resimlerin path'ini kolayca alabilirsin.
ayrıca assetler ile hiç uğraşmak istemiyorsan şu pakete bakıp çok daha temiz bir kullanımla assetlerini projene entegre edebilirsin.
https://pub.dev/packages/flutter_gen_runner

**Comment by umutsa177** [comment]
İssue ' un için teşekkür ederim.
