### ISSUE TITLE
widget'lara metot yerine subwidget haline getirme

### ISSUE THREAD

**Issue by akaanuzman** [umutsa177/travel_App#4]
https://github.com/umutsa177/travel_App/blob/57e524eb3f1b2ee81a4e409fc37e02db990d21d1/lib/views/home_view.dart#L101

ben de önceden bu şekilde hep metot halinde widgetları dışarı çıkarırdım ama ayrı bir subwidget haline getirip bunu ilgili view klasörünün altına subviews subwidgets vs. gibi bi klasörün altına toplayabilirsin. 
atomic design pattern de uygulayabilirsin ama zorlayabiliyor bazı durumlarda :D

**Comment by akaanuzman** [comment]
bu arada eline emeğine sağlık 👌🏻

**Comment by umutsa177** [comment]
İssue ' un için teşekkürler.
